name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - id: cache-node-modules
      if: github.run_attempt == '1'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install node packages
      if: github.run_attempt != '1' || steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: nick-invision/retry@0711ba3d7808574133d713a0d92d2941be03a350
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: npm ci
