name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      with:
        fetch-depth: 0

    - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version-file: '.nvmrc'
        cache: npm

    - name: Install NPM
      run: npm ci
