name: Run e2e performance regression tests

on:
  push:

jobs:
  e2e-tests:
    name: "Run e2e performance regression tests"
    runs-on: ubuntu-latest
    steps:
      - uses: Expensify/App/.github/actions/composite/setupNode@main

      - uses: ruby/setup-ruby@eae47962baca661befdfd24e4d6c34ade04858f7
        with:
          ruby-version: '2.7'
          bundler-cache: true

      # Cache gradle to improve Android build time
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: npm run android-build-e2e

      - name: Copy APK
        run: cp android/app/build/outputs/apk/e2eRelease/app-e2eRelease.apk app-e2eRelease.apk

      - name: Zip built APK
        run: zip app-e2eRelease.apk.zip app-e2eRelease.apk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Schedule test run
        uses: realm/aws-devicefarm/test-application@master
        with:
          name: App E2E Performance Regression Tests
          project_arn: ${{ secrets.AWS_PROJECT_ARN }}
          device_pool_arn: ${{ secrets.AWS_DEVICE_POOL_ARN }}
          app_file: app-e2eRelease.apk
          app_type: ANDROID_APP
          test_type: APPIUM_NODE
          test_package_file: app-e2eRelease.apk.zip
          test_package_type: APPIUM_NODE_TEST_PACKAGE
          test_spec_file: tests/e2e/TestSpec.yml
          test_spec_type: APPIUM_NODE_TEST_SPEC
          remote_src: false
          file_artifacts: Customer Artifacts.zip

      - name: Unzip Artifacts
        run: unzip Customer\ Artifacts.zip

      - name: debug
        run: find .

      - name: Print results
        run: cat ./Host_Machine_Files/\$WORKING_DIRECTORY/output.md

      - name: Set env
        run: echo "OUTPUT=$(cat ./Host_Machine_Files/$WORKING_DIRECTORY/output.md)" >> $OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ env.OUTPUT }}
            })
