name: Run e2e performance regression tests

on:
  push:

jobs:
  e2e-tests:
    if: ${{ github.event.label.name == 'e2e' }}
    name: "Run e2e performance regression tests"
    runs-on: macos-latest
    steps:
      - uses: Expensify/App/.github/actions/composite/setupNode@main

      - name: Build APK
        run: npm run android-build-e2e

      - name: Zip built APK
        run: zip android/app/build/outputs/apk/e2eRelease/app-e2eRelease.apk android/app/build/outputs/apk/e2eRelease/app-e2eRelease.apk.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Schedule test run
        uses: realm/aws-devicefarm/test-application@master
        with:
          name: run_with_uploads
          project_arn: ${{ secrets.AWS_PROJECT_ARN }}
          app_file: android/app/build/outputs/apk/e2eRelease/app-e2eRelease.apk
          app_type: ANDROID_APP
          test_type: APPIUM_NODE
          test_package_file: android/app/build/outputs/apk/e2eRelease/app-e2eRelease.apk.zip
          test_package_type: APPIUM_NODE_TEST_PACKAGE
          test_spec_file: tests/e2e/TestSpec.yml
          test_spec_type: APPIUM_NODE_TEST_SPEC
          remote_src: false
