name: Reassure Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  perf-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup NodeJS
        uses: Expensify/App/.github/actions/composite/setupNode@main

      - name: Run performance testing script
        shell: bash
        run: |
          set -e 
          BASELINE_BRANCH=${BASELINE_BRANCH:="main"}
          git fetch origin
          git switch "$BASELINE_BRANCH"
          npm install --force
          npx reassure --baseline
          git switch --detach -
          npm install --force
          npx reassure --branch

      - name: Run Danger.js
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
